// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirpyredupgrade.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const chirpyRedUpgrade = `-- name: ChirpyRedUpgrade :one

UPDATE users
SET is_chirpy_red = TRUE, updated_at = NOW()
where id = $1
returning id, created_at, updated_at, email, is_chirpy_red
`

type ChirpyRedUpgradeRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Email       string
	IsChirpyRed bool
}

func (q *Queries) ChirpyRedUpgrade(ctx context.Context, id uuid.UUID) (ChirpyRedUpgradeRow, error) {
	row := q.db.QueryRowContext(ctx, chirpyRedUpgrade, id)
	var i ChirpyRedUpgradeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.IsChirpyRed,
	)
	return i, err
}
