// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verifyrefreshtoken.sql

package database

import (
	"context"
)

const verifyRefreshToken = `-- name: VerifyRefreshToken :one

select token, created_at, updated_at, expires_at, revoked_at, user_id from refresh_tokens
where token = $1
`

func (q *Queries) VerifyRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, verifyRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
	)
	return i, err
}
